# Generated by Django 4.0.5 on 2022-07-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_token',
            new_name='forget_password_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_varified',
            new_name='is_email_varified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='forget_password',
        ),
        migrations.AddField(
            model_name='user',
            name='email_varification_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
