# Generated by Django 4.0.5 on 2022-08-27 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ManyToManyField(related_name='skill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='professional_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('From', models.DateField(blank=True, null=True)),
                ('to', models.DateField(blank=True, null=True)),
                ('is_currently_working', models.BooleanField(default=False)),
                ('location', models.TextField(blank=True, null=True)),
                ('work_responsibility', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professionaldetail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
