# Generated by Django 4.0.5 on 2022-08-27 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_skill_user_skill_user_professional_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='professional_details',
            new_name='professional_detail',
        ),
        migrations.CreateModel(
            name='user_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('project_desc', models.TextField()),
                ('project_link', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
